"use client"

import Link from "next/link"
import { useParams } from "next/navigation"
import { useT } from "@/lib/i18n"
import { PublicLayoutHeader, PublicLayoutFooter } from "@/components/landing/public-layout"
import { ArrowLeft } from "lucide-react"

export default function PrivacyPage() {
  const t = useT()
  const params = useParams()
  const locale = (params?.locale as string) || "en"

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <PublicLayoutHeader />
      <main className="flex-1 max-w-3xl mx-auto w-full px-4 py-10">
        <Link
          href={locale === "en" ? "/en" : `/${locale}`}
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          {t("pages.backToHome")}
        </Link>
        <h1 className="text-2xl font-bold text-foreground mb-2">Terms and Conditions and Privacy Policy for Lendfinex</h1>
        <p className="text-sm text-muted-foreground mb-8">Effective Date: March 2025</p>
        <div className="prose prose-sm dark:prose-invert max-w-none space-y-4 text-muted-foreground text-sm leading-relaxed">
          <p>
            These Terms and Conditions (the &ldquo;Terms&rdquo;) govern the use of Lendfinex (the &ldquo;Bot&rdquo;), a proprietary automated tool designed to maximize lending profits on the Bitfinex cryptocurrency exchange (the &ldquo;Exchange&rdquo;) by optimizing lending offers, managing collateral, and executing lending transactions in accordance with predefined algorithms. By accessing, installing, or using the Bot (collectively, &ldquo;Using&rdquo; or &ldquo;Use&rdquo;), you (the &ldquo;User&rdquo; or &ldquo;You&rdquo;) agree to be bound by these Terms, including all applicable laws, regulations, and the Bitfinex Terms of Service (available at [Bitfinex Terms Link], the &ldquo;Exchange Terms&rdquo;). If You do not agree to all of these Terms, You must immediately cease all Use of the Bot and uninstall it.
          </p>
          <p>
            The Bot is owned and operated by [Our Company Name] (the &ldquo;Company,&rdquo; &ldquo;We,&rdquo; &ldquo;Us,&rdquo; or &ldquo;Our&rdquo;). These Terms are entered into between You and the Company, and govern all Use of the Bot, including any associated services, updates, or support provided by the Company. The primary purpose of these Terms is to protect the Company, its affiliates, employees, agents, and licensors (collectively, &ldquo;Our Parties&rdquo;) from liability, loss, and harm arising from Your Use of the Bot, while clarifying Your rights and obligations in connection with the Bot.
          </p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">1. Definitions</h2>
          <p><strong>1.1</strong> &ldquo;Bot&rdquo; means Lendfinex, the automated software application developed by the Company to interact with the Bitfinex API to facilitate, optimize, and execute cryptocurrency lending transactions on behalf of the User, with the goal of maximizing lending profits. The Bot includes all updates, modifications, patches, and related documentation provided by the Company.</p>
          <p><strong>1.2</strong> &ldquo;Bitfinex API&rdquo; means the application programming interface provided by Bitfinex that allows third-party software (including the Bot) to access and interact with the User&rsquo;s Bitfinex account.</p>
          <p><strong>1.3</strong> &ldquo;Lending Transactions&rdquo; means any transactions initiated by the Bot on the User&rsquo;s behalf on Bitfinex.</p>
          <p><strong>1.4</strong> &ldquo;Collateral&rdquo; means any cryptocurrency or other assets pledged by a borrower on Bitfinex to secure a loan from the User.</p>
          <p><strong>1.5</strong> &ldquo;API Key&rdquo; means the unique authentication credentials generated by the User on Bitfinex and provided to the Bot.</p>
          <p><strong>1.6</strong> &ldquo;Profits&rdquo; means the net returns generated from Lending Transactions.</p>
          <p><strong>1.7</strong> &ldquo;Losses&rdquo; means any financial loss, liability, damage, cost, or expense incurred by Our Parties or the User as a result of Use of the Bot.</p>
          <p><strong>1.8</strong> &ldquo;Regulatory Requirements&rdquo; means all applicable laws, regulations, rules, and guidelines governing cryptocurrency lending, automated trading, and digital asset services.</p>
          <p><strong>1.9</strong> &ldquo;Personal Data&rdquo; means any information relating to an identified or identifiable natural person, including but not limited to name, email address, phone number, IP address, device information, and Bitfinex account-related metadata (excluding API secret and sensitive account credentials).</p>
          <p><strong>1.10</strong> &ldquo;Non-Personal Data&rdquo; means any data that cannot be used to identify a specific Data Subject, including anonymized Bot performance data and aggregated lending transaction statistics.</p>
          <p><strong>1.11</strong> &ldquo;Data Processing&rdquo; means any operation performed on Personal Data or Non-Personal Data, including collection, storage, use, disclosure, and deletion.</p>
          <p><strong>1.12</strong> &ldquo;Data Breach&rdquo; means a security incident resulting in accidental or unlawful destruction, loss, alteration, or unauthorized disclosure of Personal Data.</p>
          <p><strong>1.13</strong> &ldquo;Anonymization&rdquo; means the process of transforming Personal Data into a form that cannot be associated with a specific Data Subject.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">2. Eligibility and User Obligations</h2>
          <p><strong>2.1 Eligibility:</strong> You represent and warrant that You are at least 18 years of age and have the legal capacity to enter into these Terms. You further represent that You are a registered user of Bitfinex with a valid account in good standing, have agreed to the Exchange Terms, and are not prohibited from using cryptocurrency lending services or automated bots.</p>
          <p><strong>2.2 API Key Responsibility:</strong> You are solely responsible for generating, securing, and managing Your Bitfinex API Key. You agree to keep it confidential, enable 2FA, configure minimum necessary permissions, and revoke immediately if unauthorized access is suspected.</p>
          <p><strong>2.3 Compliance with Exchange Terms:</strong> You agree to comply with all Exchange Terms. The Bot operates within that framework; any violation may result in account suspension and liability.</p>
          <p><strong>2.4 Prohibited Uses:</strong> You agree not to use the Bot for illegal purposes, modify or reverse engineer it, exceed API limits, share credentials, or violate Regulatory Requirements.</p>
          <p><strong>2.5 User Monitoring:</strong> You agree to actively monitor Your Bitfinex account and Lending Transactions initiated by the Bot.</p>
          <p><strong>2.6 Data-Related Obligations:</strong> You represent that: (a) You have the legal right to provide Personal Data to the Company; (b) You have obtained any necessary consent from third parties; (c) You will not provide false or misleading Personal Data; (d) You will notify the Company of changes to Your Personal Data; and (e) You will comply with applicable data protection laws.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">3. Bot Functionality and Limitations</h2>
          <p><strong>3.1 Bot Purpose:</strong> The Bot optimizes Lending Transactions on Bitfinex to maximize profits. The Bot analyzes market conditions and executes transactions per predefined parameters.</p>
          <p><strong>3.2 No Guarantee of Profits:</strong> You acknowledge that the Bot does not guarantee Profits. All Lending Transactions involve risks including market volatility, borrower default, liquidation losses, and API failures. The Company shall not be liable for any Losses.</p>
          <p><strong>3.3–3.5</strong> Bot Updates, Limitations, and Collateral Management: The Company may update or discontinue the Bot at any time. Performance depends on factors outside the Company&rsquo;s control. The Company does not guarantee liquidation will recover all lent funds.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">4. Liability Limitations and Indemnification</h2>
          <p><strong>4.1 No Liability for Losses:</strong> Our Parties shall not be liable for any direct, indirect, incidental, consequential, or exemplary damages arising from Your Use of the Bot.</p>
          <p><strong>4.2 Exceptions:</strong> Our Parties shall only be liable for damages directly caused by gross negligence, willful misconduct, or fraud. Liability shall not exceed fees paid in the 12 months prior to the claim.</p>
          <p><strong>4.3 Indemnification:</strong> You agree to indemnify Our Parties from claims arising from Your Use of the Bot, violation of Terms, API Key compromise, Lending Transactions, and breach of data protection laws.</p>
          <p><strong>4.4 No Warranty:</strong> The Bot is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of merchantability, fitness, or that it will be error-free or generate Profits.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">5. Intellectual Property Rights</h2>
          <p>The Bot and all intellectual property rights are the exclusive property of the Company. You may not copy, modify, reverse engineer, or use the Company&rsquo;s or Bitfinex&rsquo;s intellectual property without permission.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">6. Account Security and Data Protection</h2>
          <p><strong>6.1 Account Security:</strong> You are solely responsible for Your Bitfinex account and API Key security. The Company does not store Your API secret.</p>
          <p><strong>6.2 Data Collection and Use:</strong> The Company may collect API Key metadata, Lending Transaction history, Bot performance data, and account balance information. Data is not shared with third parties except as required by law or to protect rights.</p>
          <p><strong>6.3 Data Retention:</strong> Data is retained as long as necessary to provide the Bot or as required by law. You may request deletion subject to legal requirements.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">7. Termination</h2>
          <p><strong>7.1 Termination by You:</strong> You may terminate by ceasing Use, uninstalling, and revoking the API Key. Upon termination, the Company shall cease Data Processing and delete or anonymize Your Personal Data within a reasonable period, unless prohibited by law.</p>
          <p><strong>7.2 Termination by the Company:</strong> The Company may terminate at any time for violation of Terms, Exchange Terms, or Regulatory Requirements; false information; account suspension; or risk to Our Parties. Same data deletion obligations apply.</p>
          <p><strong>7.3 Effects:</strong> Upon termination, all licenses end. No refunds. Sections 4, 5, 7.3, 8, 9, and 11 survive.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">8. Governing Law and Dispute Resolution</h2>
          <p>These Terms are governed by the laws of [Insert Jurisdiction]. Disputes shall be resolved through good-faith negotiation; if unresolved within 30 days, either party may initiate legal action. No class actions; jury trial waived.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">9. General Provisions</h2>
          <p>Entire agreement; severability; no waiver; assignment restrictions; notices; force majeure; regulatory compliance; UCC protections; fees; amendments. Data-related inquiries: [Insert Data Protection Contact Information].</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">10. Additional Protections for Our Parties</h2>
          <p>No fiduciary duty; no liability for third-party services or data breaches; recovery of costs; no liability for market volatility or borrower default; indemnification for regulatory penalties including data protection violations.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8 mb-2">11. Privacy Policy</h2>
          <p>This Privacy Policy regulates the collection, use, storage, disclosure, and protection of Your Personal Data and Non-Personal Data. It is an integral part of the Main Terms. By using the Bot, You agree to this Privacy Policy. If You do not agree, cease using the Bot immediately.</p>

          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">11.1 Scope of Data Collection</h3>
          <p><strong>11.1.1</strong> The Company collects only the minimum necessary data required for Bot functions, following the principle of &ldquo;minimum necessity&rdquo;.</p>
          <p><strong>11.1.2 Personal Data collected:</strong> (a) Identification information (name, email, phone) when You provide for support; (b) Device information (model, OS, IP, browser); (c) Bitfinex account metadata (account ID, non-sensitive lending records); (d) Other data You actively provide.</p>
          <p><strong>11.1.3 Non-Personal Data collected:</strong> (a) Bot performance data (run time, response speed, error logs); (b) Aggregated anonymized lending data; (c) Public Bitfinex market data; (d) Anonymized behavior data.</p>
          <p><strong>11.1.4 Prohibited collection:</strong> API secret, bank card, ID number; irrelevant privacy information; illegal or unauthorized data. You bear all risks for providing prohibited data.</p>

          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">11.2 Methods of Data Collection</h3>
          <p><strong>11.2.1 Active Collection:</strong> Information You submit during registration, login, or use; Bitfinex account metadata via API (within Your authorization scope); feedback and support requests.</p>
          <p><strong>11.2.2 Automatic Collection:</strong> Device info, operation data, IP address during Bot operation. No additional authorization required for necessary operation data.</p>
          <p><strong>11.2.3 Third-Party Collection:</strong> The Company does not collect data through third parties. Bitfinex processes Your data per its privacy policy. The Company obtains only necessary data via API within Your authorization.</p>

          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">11.3 Purposes of Data Use</h3>
          <p><strong>11.3.1 Core Functions:</strong> Account balance, lending history, optimizing quotes, executing transactions, monitoring collateral, device compatibility.</p>
          <p><strong>11.3.2 Bot Optimization:</strong> Troubleshooting, fixing vulnerabilities, analyzing market trends, improving algorithms.</p>
          <p><strong>11.3.3 Service Support:</strong> Responding to support requests; sending update notifications; informing of regulatory or API changes.</p>
          <p><strong>11.3.4 Compliance and Risk Control:</strong> Fraud prevention, regulatory cooperation, fulfilling Main Terms obligations. Regular compliance audits.</p>
          <p><strong>11.3.5 Restrictions:</strong> Data used only for stated purposes; no use beyond scope without Your consent; minimum necessity; no unauthorized access or disclosure.</p>

          <h3 className="text-base font-semibold text-foreground mt-6 mb-2">11.4 Data Storage and Security Protection</h3>
          <p><strong>11.4.1 Data Storage:</strong> Data stored in secure servers in [Insert Storage Jurisdiction]. Storage period is minimum necessary; then deletion or anonymization. Entrustment agreements require compliance; records kept 3+ years. No overseas storage of Personal Data; outbound transfer only after security assessment if required.</p>
          <p><strong>11.4.2 Security Measures:</strong> Encryption (SSL/TLS), encrypted storage, firewalls, intrusion detection, security audits; data security management, access control, personnel training; incident response plan, timely notification of breaches.</p>
          <p><strong>11.4.3 Liability Exemption:</strong> The Company is not liable for data leakage, loss, or tampering caused by: (a) Force majeure; (b) Third-party factors (Bitfinex API, hackers, third-party providers); (c) Your faults (API secret leakage, device issues).</p>
        </div>
      </main>
      <PublicLayoutFooter />
    </div>
  )
}
